services:
  OxidEsales\EshopCommunity\Internal\Module\State\ModuleStateServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\State\ModuleStateService
    public: true
    autowire: true